### ISSUE TITLE
Blacklist feature not working for sites

### ISSUE THREAD

**Issue by pr0l0g** [AtoraSuunva/Booru-Discord#37] opened 2020-10-12 09:34 UTC
## Issue 
Blacklist command not having any effect for sites.

---

## Example
<img width="439" alt="ex1" src="https://user-images.githubusercontent.com/18596266/95730534-aa72e080-0c7e-11eb-872f-ec6ee7665b0a.png">

<img width="445" alt="ex2" src="https://user-images.githubusercontent.com/18596266/95730545-ae9efe00-0c7e-11eb-8a55-b62595eef356.png">

---

## Steps to replicate
Simply attempt to blacklist a site.

**Comment by AtoraSuunva** [comment] 2020-10-14 04:40
Odd, I couldn't reproduce this bug on 4/4 servers I tested this on. Mind letting me know the server ID this is happening on?
![image](https://user-images.githubusercontent.com/15206032/95944250-53345380-0dd7-11eb-8c9e-75eae5a7e49e.png)

**Comment by pr0l0g** [comment] 2020-10-14 14:52
Of course; the ID is 359279749610078242.

**Comment by AtoraSuunva** [comment] 2020-10-15 06:16
Should be fixed in https://github.com/AtlasTheBot/Booru-Discord/pull/38
It was an oversight in how I was dealing with settings for new guilds after the settings rework

**Closed as completed by AtoraSuunva** 2020-10-15 06:16 UTC
Labels: bug
